name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
   

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

   

  

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Geckodriver
      uses: browser-actions/setup-geckodriver@v0.0.0

      #gradle
    - name: setup gradlew
      run: chmod +x gradlew

    - name: execute
      run: ./gradlew test

    #artefak
    - name: artifak
      uses: actions/upload-artifact@v4.3.3
      if: always()
      with:
        name: cucumber-report
        path: target


    #deploy to github pages
    - name: deploy report to github pages
      if: always()
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        Publish_token: ${{secrets.GITHUB_TOKEN}}
        Publish_Dir: reports
